# This file was generated by GoReleaser. DO NOT EDIT.
cask "dark-factory" do
  version "0.193.0"

  on_macos do
    on_intel do
      sha256 "51178ab3389759036959035d643bf86df63c351827279148c666c1c46da65963"
      url "https://github.com/bborbe/dark-factory/releases/download/v#{version}/dark-factory_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "82a07c786a91226856a8e02a5aa2c0e9038b08877565bb319471f98fc5171e05"
      url "https://github.com/bborbe/dark-factory/releases/download/v#{version}/dark-factory_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "67e5eecadc12dd5b08c554c0d2dfb8ae80b2f8eed9b4cf320ffeae2d04b83441"
      url "https://github.com/bborbe/dark-factory/releases/download/v#{version}/dark-factory_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "9345c4249473bdd05259ee493cbd6a07991eb7bd18e03049b5f8cf201e461df1"
      url "https://github.com/bborbe/dark-factory/releases/download/v#{version}/dark-factory_linux_arm64.tar.gz"
    end
  end

  name "dark-factory"
  desc "Spec-driven autonomous code generation pipeline"
  homepage "https://github.com/bborbe/dark-factory"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "dark-factory"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/dark-factory"]
  end

  # No zap stanza required

end
