# This file was generated by GoReleaser. DO NOT EDIT.
cask "dark-factory" do
  version "0.196.0"

  on_macos do
    on_intel do
      sha256 "d9249cc7170f102b3105d8b41fa9813e26a74117c937f748dd89a5692d3eab33"
      url "https://github.com/bborbe/dark-factory/releases/download/v#{version}/dark-factory_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "bff7703b326379e9fbf7d0d27dd5f853c030675a6481320108157a3d3c12256f"
      url "https://github.com/bborbe/dark-factory/releases/download/v#{version}/dark-factory_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "559d9988591057de88f4d529d7a5d9b104b448f9e211afbd748005f89e740031"
      url "https://github.com/bborbe/dark-factory/releases/download/v#{version}/dark-factory_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "13f5d18f7f8b6208051a78b667633e366acaf42f7a1055598dfc6a3a3ad2dfc9"
      url "https://github.com/bborbe/dark-factory/releases/download/v#{version}/dark-factory_linux_arm64.tar.gz"
    end
  end

  name "dark-factory"
  desc "Spec-driven autonomous code generation pipeline"
  homepage "https://github.com/bborbe/dark-factory"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "dark-factory"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/dark-factory"]
  end

  # No zap stanza required

end
