# This file was generated by GoReleaser. DO NOT EDIT.
cask "distill" do
  version "0.6.0"

  on_macos do
    on_intel do
      sha256 "700738eacb71c854e18c1d83fb8fc80f794851e61550240ea9f0041cee7c0d89"
      url "https://github.com/bborbe/distill/releases/download/v#{version}/distill_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "a912135ddb3465816e326741042f335c4092b325fd31e4fed530bff323b2a637"
      url "https://github.com/bborbe/distill/releases/download/v#{version}/distill_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "52686df1b0a1ac9341cd0ae33089af30699c6809c6f232f988646d86605fce05"
      url "https://github.com/bborbe/distill/releases/download/v#{version}/distill_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "b5e7f1cc3f8bdd873e930222557c5fe1697e037571cada880ec4cab603f804d3"
      url "https://github.com/bborbe/distill/releases/download/v#{version}/distill_linux_arm64.tar.gz"
    end
  end

  name "distill"
  desc "Compile per-rule markdown files into one AI-targeted file (e.g. CLAUDE.md)"
  homepage "https://github.com/bborbe/distill"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "distill"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/distill"]
  end

  # No zap stanza required

end
