# This file was generated by GoReleaser. DO NOT EDIT.
cask "vault-cli" do
  version "0.130.0"

  on_macos do
    on_intel do
      sha256 "3824e4fd9735053f0fa4ece5d1d2ba1411f7f879db5d7413d063c6a7eb15f810"
      url "https://github.com/bborbe/vault-cli/releases/download/v#{version}/vault-cli_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "e634271284a929f181bb8aea745b24791c66ae365b7bbd85547015c17fcb95ee"
      url "https://github.com/bborbe/vault-cli/releases/download/v#{version}/vault-cli_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "cea34a7b9140d2f1a87ea30d7b0377c9d19002d8990c67de8144c64754b8c4c6"
      url "https://github.com/bborbe/vault-cli/releases/download/v#{version}/vault-cli_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "3ea30819377d8b3aa9b53d5290e4ad344f7feecdd43affdb8d8c12d6f4543f0b"
      url "https://github.com/bborbe/vault-cli/releases/download/v#{version}/vault-cli_linux_arm64.tar.gz"
    end
  end

  name "vault-cli"
  desc "Obsidian vault CLI for tasks, goals, themes, and objectives"
  homepage "https://github.com/bborbe/vault-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "vault-cli"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/vault-cli"]
  end

  # No zap stanza required

end
