# Hand-maintained cask (not GoReleaser-generated): vault-ui is a Python
# package distributed as a wheel, installed as a uv tool. The version and
# sha256 are bumped by .github/workflows/update-vault-ui-cask.yml when a new
# vault-ui release is published.
cask "vault-ui" do
  version "0.64.0"
  sha256 "d56723747d0f7c5216d9697eb18f3d24cb76a94ef78b8036e474ad4e606cf74b"

  url "https://github.com/bborbe/vault-ui/releases/download/v#{version}/vault_ui-#{version}-py3-none-any.whl"

  name "vault-ui"
  desc "Obsidian task board web UI (FastAPI service)"
  homepage "https://github.com/bborbe/vault-ui"

  depends_on formula: "uv"

  # postflight does not inherit the user shell's PATH — the uv formula was
  # just poured, so resolve it via the Homebrew prefix.
  uv = File.join(HOMEBREW_PREFIX, "bin", "uv")

  postflight do
    system_command uv,
                   args: ["tool", "install", "--force",
                          "https://github.com/bborbe/vault-ui/releases/download/v#{version}/vault_ui-#{version}-py3-none-any.whl"],
                   print_stdout: true

    # Register the launchd agent that keeps the board on :8000. The wheel is a
    # zip, so Homebrew stages it unpacked — install from the release URL instead
    # of staged_path (the sha256 above already validated the artifact).
    home = Dir.home

    # vault-ui refuses to start without a config (load_config hard-requires
    # it), and the vault list it serves comes from the `vaults:` section of
    # that config. The wheel install resolves the XDG path
    # (~/.config/vault-ui/config.yaml) — the legacy repo-root config.yaml
    # only exists in a git clone. When absent, generate the config from the
    # vault-cli registry (the documented prerequisite) so `brew install
    # vault-ui` ends with a working board; the user can edit it afterwards.
    config_dir = File.join(home, ".config", "vault-ui")
    config_path = File.join(config_dir, "config.yaml")
    unless File.exist?(config_path)
      vaults_yaml = ""
      begin
        out = IO.popen(["vault-cli", "config", "list", "--output", "json"]) { |io| io.read }
        JSON.parse(out).each { |v| vaults_yaml += "  #{v["name"]}:\n" }
      rescue StandardError
        vaults_yaml = ""
      end
      FileUtils.mkdir_p(config_dir)
      File.write(config_path, <<~YAML)
        # Generated by the vault-ui cask (brew install) from `vault-cli config list`.
        # Edit to taste; the `vaults:` keys must match vault names in vault-cli's registry.
        host: 127.0.0.1
        port: 8000
        max_concurrent_sessions: 20
        vaults:
        #{vaults_yaml}
      YAML
    end

    plist_path = File.expand_path("~/Library/LaunchAgents/com.github.bborbe.vault-ui.plist")
    FileUtils.mkdir_p(File.dirname(plist_path))
    File.write(plist_path, <<~PLIST)
      <?xml version="1.0" encoding="UTF-8"?>
      <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
      <plist version="1.0">
      <dict>
        <key>Label</key>
        <string>com.github.bborbe.vault-ui</string>
        <key>ProgramArguments</key>
        <array>
          <string>#{home}/.local/bin/vault-ui</string>
        </array>
        <key>RunAtLoad</key>
        <true/>
        <key>KeepAlive</key>
        <true/>
        <key>StandardOutPath</key>
        <string>#{home}/Library/Logs/vault-ui.log</string>
        <key>StandardErrorPath</key>
        <string>#{home}/Library/Logs/vault-ui.log</string>
        <key>EnvironmentVariables</key>
        <dict>
          <key>HOME</key>
          <string>#{home}</string>
          <key>PATH</key>
          <string>/opt/homebrew/bin:/usr/local/bin:#{home}/.local/bin:/usr/bin:/bin:/usr/sbin:/sbin</string>
        </dict>
      </dict>
      </plist>
    PLIST

    # Register and start the agent, best-effort: launchd domain management
    # (bootstrap/bootout) is unavailable from some contexts (SSH, sandboxed
    # install), so a failure here must not fail the cask install. kickstart
    # covers both cases — a fresh job and an already-loaded one (upgrade).
    system_command "launchctl",
                   args: ["bootout", "gui/#{Process.uid}", "com.github.bborbe.vault-ui"],
                   must_succeed: false,
                   print_stdout: true
    system_command "launchctl",
                   args: ["bootstrap", "gui/#{Process.uid}", plist_path],
                   must_succeed: false,
                   print_stdout: true
    system_command "launchctl",
                   args: ["kickstart", "-k", "gui/#{Process.uid}/com.github.bborbe.vault-ui"],
                   must_succeed: false,
                   print_stdout: true
  end

  uninstall_postflight do
    system_command "launchctl",
                   args: ["bootout", "gui/#{Process.uid}", "com.github.bborbe.vault-ui"],
                   must_succeed: false,
                   print_stdout: true
    system_command uv,
                   args: ["tool", "uninstall", "vault-ui"],
                   must_succeed: false,
                   print_stdout: true
  end

  caveats do
    <<~EOS
      vault-ui is installed as a uv tool and registered as a launchd agent
      (com.github.bborbe.vault-ui) serving http://127.0.0.1:8000.

      Prerequisites — the board needs the vault registry, which vault-ui
      reads from vault-cli:
        brew install bborbe/tap/vault-cli
        # then configure ~/.vault-cli/config.yaml (see the vault-cli docs)

      Its own config was generated at ~/.config/vault-ui/config.yaml from the
      vault-cli registry (edit it to change which vaults the board shows).
      The agent restarts on failure (KeepAlive); logs land in
      ~/Library/Logs/vault-ui.log.

      If the service is not running (launchd could not be managed from the
      install context), start it with:
        launchctl bootstrap gui/$(id -u) ~/Library/LaunchAgents/com.github.bborbe.vault-ui.plist
        # or, when already loaded: launchctl kickstart -k gui/$(id -u)/com.github.bborbe.vault-ui

      Update: brew upgrade vault-ui
    EOS
  end
end
