# This file was generated by GoReleaser. DO NOT EDIT.
cask "vault-cli" do
  version "0.140.0"

  on_macos do
    on_intel do
      sha256 "7ea2282e8b158feb6ae73d1aaa25773abdb8bc9e7558c6630352e700dccf9c26"
      url "https://github.com/bborbe/vault-cli/releases/download/v#{version}/vault-cli_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "716a8891b0b69a720ace8af837a315b78fd28ab3ff4f2728cfe91b827bea12ae"
      url "https://github.com/bborbe/vault-cli/releases/download/v#{version}/vault-cli_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "b221eff95de02f1c475be6e951e371d4cc3d1d4dd45029e4eea5e1ac88b42afd"
      url "https://github.com/bborbe/vault-cli/releases/download/v#{version}/vault-cli_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "535d2f0a806dd9559e804afbf2c80909dcb7f0e5621114f1b4b163375b5e95f0"
      url "https://github.com/bborbe/vault-cli/releases/download/v#{version}/vault-cli_linux_arm64.tar.gz"
    end
  end

  name "vault-cli"
  desc "Obsidian vault CLI for tasks, goals, themes, and objectives"
  homepage "https://github.com/bborbe/vault-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "vault-cli"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/vault-cli"]
  end

  # No zap stanza required

end
