# This file was generated by GoReleaser. DO NOT EDIT.
cask "vault-cli" do
  version "0.114.4"

  on_macos do
    on_intel do
      sha256 "25e7433da37156cca5f9603ec6ea1a98ccedb5d211a5ecca753a7dc0ee9a7c0f"
      url "https://github.com/bborbe/vault-cli/releases/download/v#{version}/vault-cli_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "f0b1b83a524c96d9d019cc9aec249fc36dc09ad7ab07c3450e433ad376c4bfb7"
      url "https://github.com/bborbe/vault-cli/releases/download/v#{version}/vault-cli_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "4b53ae474fda6e842311b87df3c9345e3126dc8682ccca1e2607a7e1e5fb3beb"
      url "https://github.com/bborbe/vault-cli/releases/download/v#{version}/vault-cli_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "c64add47d68f139a2cb5a9f0e3bf0b3c6dcc01308cbaab9863782bf848fd189b"
      url "https://github.com/bborbe/vault-cli/releases/download/v#{version}/vault-cli_linux_arm64.tar.gz"
    end
  end

  name "vault-cli"
  desc "Obsidian vault CLI for tasks, goals, themes, and objectives"
  homepage "https://github.com/bborbe/vault-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "vault-cli"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/vault-cli"]
  end

  # No zap stanza required

end
